### ISSUE TITLE
YouTube Videos Aren't Responsive

### ISSUE THREAD

**Issue by attheshow** [getgrav/grav-theme-soraarticle#1]
This theme is awesome! I have noticed one issue when viewing YouTube videos in the headers of posts. They don't appear to be responsive and are chopped off when viewing in a mobile device. I've attached a screenshot for reference. Thanks again for the awesome theme!
![screen shot 2015-09-28 at 9 58 06 am](https://cloud.githubusercontent.com/assets/191008/10137488/d0f6867a-65c7-11e5-9a4a-f1f36182cb9a.png)

From: [FleetThought.com post](http://www.fleetthought.com/blog/body-language-tells-of-martin-shkreli-turing-pharmaceuticals)

**Comment by hexplor** [comment]
Thanks, I'm going to work on that issue and will release needed fix.
