### ISSUE TITLE
Make theme admin-plugin compatible

### ISSUE THREAD

**Issue by c4tz** [getgrav/grav-theme-soraarticle#3]
Hi,

this template needs to be made compatible with the admin plugin. If you edit & save a the "About me" widget, for example, it will cause an 400-Error, because it will be saved with the "Blog"-Display-Template. (see https://github.com/getgrav/grav-plugin-admin/issues/404)

Best regards, BlkChockr

**Comment by hexplor** [comment]
Hey, thanks for reporting. I'm gonna check carefully SoraArticle with admin plugin and I will release update if needed :)

**Comment by hexplor** [comment]
Hey. Thanks for this report. It's was quite major issue which probably affect some of my other themes. Anyways, releasing update now with proper fix.

**Comment by hexplor** [comment]
released: https://github.com/getgrav/grav-theme-soraarticle/commit/41012d6390baf7fba798e2d7e3eae7c8d085338c

**Comment by c4tz** [comment]
No Problem! I love how fast this was fixed, Grav seems to become a better and better choice :)
